# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MTA Arrival Times' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MTA Arrival Times

end

target 'MTA Arrival Times WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MTA Arrival Times WatchKit App

end

target 'MTA Arrival Times WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MTA Arrival Times WatchKit Extension
end
